version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

commands:
  configure_bundler:
    description: Configure bundler
    steps:
      - run:
          name: Configure bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - release-queue-{{ checksum ".ruby-version" }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - release-queue-{{ checksum ".ruby-version" }}
      - configure_bundler
      - run:
          name: Which bundler?
          command: bundle -v
